package router

import (
	controlleragentplatform "github.com/QuantumNous/new-api/controller/agentplatform"
	"github.com/QuantumNous/new-api/middleware"
	"github.com/gin-gonic/gin"
)

func RegisterAgentPlatformRouter(apiRouter *gin.RouterGroup) {
	agentPlatformRoute := apiRouter.Group("/agent-platform")
	agentPlatformRoute.GET("/assets/avatars/:file", controlleragentplatform.GetAgentAvatar)
	oauthRoute := agentPlatformRoute.Group("/oauth")
	{
		oauthRoute.GET("/authorize", controlleragentplatform.OAuthAuthorize)
		oauthRoute.POST("/token", controlleragentplatform.OAuthToken)
		oauthRoute.POST("/revoke", controlleragentplatform.OAuthRevoke)
	}

	agentPlatformRoute.Use(middleware.AdminAuth())
	{
		agentPlatformRoute.GET("/resources", controlleragentplatform.ListResources)
		agentPlatformRoute.POST("/assets/avatars", controlleragentplatform.UploadAgentAvatar)
		agentPlatformRoute.POST("/resources", controlleragentplatform.CreateResource)
		agentPlatformRoute.GET("/resources/:id", controlleragentplatform.GetResource)
		agentPlatformRoute.GET("/model-keys", controlleragentplatform.ListAgentModelKeys)
		agentPlatformRoute.GET("/model-keys/:token_id/models", controlleragentplatform.ListAgentModelKeyModels)
		agentPlatformRoute.GET("/mcps", controlleragentplatform.ListMcps)
		agentPlatformRoute.POST("/mcps", controlleragentplatform.CreateMcp)
		agentPlatformRoute.GET("/mcps/:id", controlleragentplatform.GetMcp)
		agentPlatformRoute.PUT("/mcps/:id", controlleragentplatform.UpdateMcp)
		agentPlatformRoute.POST("/mcps/:id/disable", controlleragentplatform.DisableMcp)
		agentPlatformRoute.POST("/mcps/:id/enable", controlleragentplatform.EnableMcp)
		agentPlatformRoute.DELETE("/mcps/:id", controlleragentplatform.DeleteMcp)
		agentPlatformRoute.GET("/skills", controlleragentplatform.ListSkills)
		agentPlatformRoute.POST("/skills", controlleragentplatform.CreateSkillEntry)
		agentPlatformRoute.GET("/skills/:id", controlleragentplatform.GetSkill)
		agentPlatformRoute.PUT("/skills/:id", controlleragentplatform.UpdateSkill)
		agentPlatformRoute.POST("/skills/:id/package", controlleragentplatform.UploadSkillPackage)
		agentPlatformRoute.GET("/skills/:id/package/download", controlleragentplatform.DownloadSkillPackage)
		agentPlatformRoute.POST("/skills/:id/disable", controlleragentplatform.DisableSkill)
		agentPlatformRoute.POST("/skills/:id/enable", controlleragentplatform.EnableSkill)
		agentPlatformRoute.DELETE("/skills/:id", controlleragentplatform.DeleteSkill)
		agentPlatformRoute.GET("/knowledge-bases", controlleragentplatform.ListKnowledge)
		agentPlatformRoute.POST("/knowledge-bases", controlleragentplatform.CreateKnowledge)
		agentPlatformRoute.GET("/knowledge-bases/:id", controlleragentplatform.GetKnowledge)
		agentPlatformRoute.PUT("/knowledge-bases/:id", controlleragentplatform.UpdateKnowledge)
		agentPlatformRoute.POST("/knowledge-bases/:id/disable", controlleragentplatform.DisableKnowledge)
		agentPlatformRoute.POST("/knowledge-bases/:id/enable", controlleragentplatform.EnableKnowledge)
		agentPlatformRoute.DELETE("/knowledge-bases/:id", controlleragentplatform.DeleteKnowledge)
		agentPlatformRoute.GET("/agents", controlleragentplatform.ListAgents)
		agentPlatformRoute.POST("/agents", controlleragentplatform.CreateAgent)
		agentPlatformRoute.GET("/agents/:id", controlleragentplatform.GetAgent)
		agentPlatformRoute.PUT("/agents/:id", controlleragentplatform.UpdateAgent)
		agentPlatformRoute.DELETE("/agents/:id", controlleragentplatform.DeleteAgent)
		agentPlatformRoute.GET("/agents/:id/versions", controlleragentplatform.ListAgentVersions)
		agentPlatformRoute.GET("/agents/:id/versions/:version/grants", controlleragentplatform.ListAgentVersionGrants)
		agentPlatformRoute.GET("/agents/:id/publish-defaults", controlleragentplatform.GetAgentPublishDefaults)
		agentPlatformRoute.POST("/agents/:id/publish", controlleragentplatform.PublishAgent)
		agentPlatformRoute.GET("/clients", controlleragentplatform.ListClients)
		agentPlatformRoute.POST("/clients", controlleragentplatform.CreateClient)
		agentPlatformRoute.GET("/clients/:id", controlleragentplatform.GetClient)
		agentPlatformRoute.PUT("/clients/:id", controlleragentplatform.UpdateClient)
		agentPlatformRoute.POST("/resources/:id/versions", controlleragentplatform.CreateResourceVersion)
		agentPlatformRoute.GET("/resources/:id/versions/:version", controlleragentplatform.GetResourceVersion)
		agentPlatformRoute.GET("/resources/:id/exposures", controlleragentplatform.ListExposures)
		agentPlatformRoute.POST("/resources/:id/exposures", controlleragentplatform.CreateExposure)
		agentPlatformRoute.GET("/resources/:id/exposures/:target", controlleragentplatform.GetExposure)
		agentPlatformRoute.PUT("/resources/:id/exposures/:target", controlleragentplatform.UpdateExposure)
		agentPlatformRoute.POST("/resources/:id/exposures/:target/revoke", controlleragentplatform.RevokeExposure)
		agentPlatformRoute.POST("/resources/:id/publish", controlleragentplatform.PublishResource)
		agentPlatformRoute.POST("/resources/:id/disable", controlleragentplatform.DisableResource)
		agentPlatformRoute.POST("/resources/:id/revoke", controlleragentplatform.RevokeResource)
		agentPlatformRoute.POST("/resources/:id/offline", controlleragentplatform.OfflineResource)
		agentPlatformRoute.POST("/resources/:id/versions/:version/rollback", controlleragentplatform.RollbackResourceVersion)
	}
}
