package router

import (
	controllerenterprise "github.com/QuantumNous/new-api/controller/enterprise"
	"github.com/QuantumNous/new-api/middleware"
	"github.com/gin-gonic/gin"
)

func RegisterEnterpriseRouter(apiRouter *gin.RouterGroup) {
	enterpriseRoute := apiRouter.Group("/enterprise")
	enterpriseRoute.Use(middleware.UserAuth())
	{
		enterpriseRoute.GET("/departments/tree", controllerenterprise.GetDepartmentTree)
		enterpriseRoute.GET("/users/:id/departments", middleware.AdminAuth(), controllerenterprise.ListUserDepartments)
		enterpriseRoute.PUT("/users/:id/departments", middleware.AdminAuth(), controllerenterprise.ReplaceUserDepartments)
		enterpriseRoute.GET("/departments/:id/members", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.ListDepartmentMembers)
		enterpriseRoute.GET("/departments/:id/budget", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.GetDepartmentBudget)
		enterpriseRoute.GET("/departments/:id/budgets", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.ListDepartmentBudgets)
		enterpriseRoute.GET("/departments/:id/budgets/:budget_id", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.GetDepartmentBudgetDetail)
		enterpriseRoute.POST("/departments/:id/budget", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.CreateDepartmentBudget)
		enterpriseRoute.GET("/quota-allocations", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.ListQuotaAllocations)
		enterpriseRoute.POST("/quota-allocations", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.CreateQuotaAllocation)
		enterpriseRoute.POST("/quota-allocations/:id/supersede", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.SupersedeQuotaAllocation)
		enterpriseRoute.POST("/quota-allocations/:id/cancel", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.CancelQuotaAllocation)
		enterpriseRoute.POST("/quota-allocations/:id/reclaim", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.ReclaimQuotaAllocation)
		enterpriseRoute.POST("/quota-allocations/:id/revoke", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.RevokeQuotaAllocation)
		enterpriseRoute.GET("/quota-requests", controllerenterprise.ListQuotaRequests)
		enterpriseRoute.POST("/quota-requests", controllerenterprise.SubmitQuotaRequest)
		enterpriseRoute.GET("/quota-requests/capability/:department_id", controllerenterprise.GetQuotaRequestCapability)
		enterpriseRoute.GET("/quota-requests/:id", controllerenterprise.GetQuotaRequest)
		enterpriseRoute.POST("/quota-requests/:id/decision", controllerenterprise.DecideQuotaRequest)
		enterpriseRoute.GET("/budget-delegations", middleware.EnterpriseDepartmentAdmin("department_id"), controllerenterprise.ListBudgetDelegations)
		enterpriseRoute.POST("/budget-delegations", middleware.EnterpriseDepartmentAdmin("source_department_id"), controllerenterprise.CreateBudgetDelegation)
		enterpriseRoute.POST("/budget-delegations/:id/supersede", middleware.EnterpriseDepartmentAdmin("source_department_id"), controllerenterprise.SupersedeBudgetDelegation)
		enterpriseRoute.POST("/departments/:id/members", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.AddDepartmentMember)
		enterpriseRoute.PUT("/departments/:id/members/:user_id/username", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.RenameDepartmentMember)
		enterpriseRoute.DELETE("/departments/:id/members/:user_id", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.DeactivateDepartmentMember)
		enterpriseRoute.POST("/departments/:id/members/:user_id/restore", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.RestoreDepartmentMember)
		enterpriseRoute.POST("/departments/:id/admins", middleware.EnterpriseAdmin(), controllerenterprise.GrantDepartmentAdmin)
		enterpriseRoute.DELETE("/departments/:id/admins/:user_id", middleware.EnterpriseAdmin(), controllerenterprise.RevokeDepartmentAdmin)
		enterpriseRoute.GET("/departments/:id/owners", middleware.EnterpriseDepartmentAdmin("id"), controllerenterprise.ListDepartmentOwners)
		enterpriseRoute.POST("/departments/:id/owners/grants", middleware.EnterpriseAdmin(), controllerenterprise.GrantDepartmentOwner)
		enterpriseRoute.POST("/departments/:id/owners/denies", middleware.EnterpriseAdmin(), controllerenterprise.DenyDepartmentOwner)
		enterpriseRoute.DELETE("/departments/:id/owners/grants/:user_id", middleware.EnterpriseAdmin(), controllerenterprise.RevokeDepartmentOwnerGrant)
		enterpriseRoute.DELETE("/departments/:id/owners/denies/:user_id", middleware.EnterpriseAdmin(), controllerenterprise.RevokeDepartmentOwnerDeny)
		enterpriseRoute.GET("/admin-actions", middleware.EnterpriseAdmin(), controllerenterprise.ListAdminActions)
		enterpriseRoute.GET("/admin-actions/:id", middleware.EnterpriseAdmin(), controllerenterprise.GetAdminAction)
		enterpriseRoute.GET("/alerts/events", middleware.EnterpriseAdmin(), controllerenterprise.ListAlertEvents)
		enterpriseRoute.GET("/alerts/department-summary", controllerenterprise.GetDepartmentRiskSummary)
		enterpriseRoute.GET("/alerts/deliveries", middleware.EnterpriseAdmin(), controllerenterprise.ListAlertDeliveries)
		enterpriseRoute.POST("/alerts/deliveries/:id/resend", middleware.EnterpriseAdmin(), controllerenterprise.ResendAlertDelivery)
		enterpriseRoute.GET("/alerts/rules", middleware.EnterpriseAdmin(), controllerenterprise.ListAlertRules)
		enterpriseRoute.GET("/alerts/rules/:id", middleware.EnterpriseAdmin(), controllerenterprise.GetAlertRule)
		enterpriseRoute.PUT("/alerts/rules", middleware.EnterpriseAdmin(), controllerenterprise.SaveAlertRule)
		enterpriseRoute.DELETE("/alerts/rules/:id", middleware.EnterpriseAdmin(), controllerenterprise.DeleteAlertRule)
		enterpriseRoute.GET("/usage/department-summary", controllerenterprise.GetDepartmentUsageSummary)
		enterpriseRoute.GET("/usage/export", controllerenterprise.ExportDepartmentUsageCSV)
		enterpriseRoute.GET("/usage/department-detail", middleware.EnterpriseAdmin(), controllerenterprise.GetDepartmentUsageDetail)
		enterpriseRoute.GET("/usage/reports", middleware.EnterpriseAdmin(), controllerenterprise.GetDepartmentUsageReportConfig)
		enterpriseRoute.PUT("/usage/reports", middleware.EnterpriseAdmin(), controllerenterprise.SaveDepartmentUsageReportConfig)
		enterpriseRoute.GET("/dingtalk/config", middleware.RootAuth(), controllerenterprise.GetDingTalkConfig)
		enterpriseRoute.PUT("/dingtalk/config", middleware.RootAuth(), controllerenterprise.SaveDingTalkConfig)
		enterpriseRoute.POST("/dingtalk/connectivity-test", middleware.RootAuth(), controllerenterprise.TestDingTalkConnectivity)
		enterpriseRoute.POST("/dingtalk/sync/full", middleware.RootAuth(), controllerenterprise.StartDingTalkFullSync)
		enterpriseRoute.GET("/dingtalk/sync/tasks/:id", middleware.RootAuth(), controllerenterprise.GetDingTalkSyncTask)
		enterpriseRoute.GET("/dingtalk/sync/logs", middleware.RootAuth(), controllerenterprise.ListDingTalkSyncLogs)
		enterpriseRoute.GET("/dingtalk/sync/conflicts", middleware.RootAuth(), controllerenterprise.ListDingTalkSyncConflicts)
		enterpriseRoute.POST("/dingtalk/sync/conflicts/:id/bind-candidate", middleware.RootAuth(), controllerenterprise.ResolveDingTalkSyncConflictWithCandidate)
	}
}
